//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", ConfigurationName="Mailer.Notifications_Port")]
    public interface Notifications_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:PerformanceMonitorMonth1", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorMonth1_Result> PerformanceMonitorMonth1Async(Mailer.PerformanceMonitorMonth1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:PerformanceMonitorMonth2", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorMonth2_Result> PerformanceMonitorMonth2Async(Mailer.PerformanceMonitorMonth2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:PerformanceMonitorMonth3", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorMonth3_Result> PerformanceMonitorMonth3Async(Mailer.PerformanceMonitorMonth3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:PerformanceMonitorApproval", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorApproval_Result> PerformanceMonitorApprovalAsync(Mailer.PerformanceMonitorApproval request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:PerformanceMonitorRejection" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorRejection_Result> PerformanceMonitorRejectionAsync(Mailer.PerformanceMonitorRejection request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:PerformanceMonitortoHRfromH" +
            "OD", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitortoHRfromHOD_Result> PerformanceMonitortoHRfromHODAsync(Mailer.PerformanceMonitortoHRfromHOD request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:StaffRequisitiontoHRfromHOD" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.StaffRequisitiontoHRfromHOD_Result> StaffRequisitiontoHRfromHODAsync(Mailer.StaffRequisitiontoHRfromHOD request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:StaffRequisitiontoMDfromHR", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.StaffRequisitiontoMDfromHR_Result> StaffRequisitiontoMDfromHRAsync(Mailer.StaffRequisitiontoMDfromHR request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:StaffRequisitionHRApproval", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.StaffRequisitionHRApproval_Result> StaffRequisitionHRApprovalAsync(Mailer.StaffRequisitionHRApproval request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:StaffRequisitionMDRejection" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.StaffRequisitionMDRejection_Result> StaffRequisitionMDRejectionAsync(Mailer.StaffRequisitionMDRejection request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:StaffRequisitiontoHRfromMD", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.StaffRequisitiontoHRfromMD_Result> StaffRequisitiontoHRfromMDAsync(Mailer.StaffRequisitiontoHRfromMD request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:ShortlistedInterviewNotice", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.ShortlistedInterviewNotice_Result> ShortlistedInterviewNoticeAsync(Mailer.ShortlistedInterviewNotice request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeProbationManagerToH" +
            "R", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationManagerToHR_Result> EmployeeProbationManagerToHRAsync(Mailer.EmployeeProbationManagerToHR request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeProbationHRToMDFD", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationHRToMDFD_Result> EmployeeProbationHRToMDFDAsync(Mailer.EmployeeProbationHRToMDFD request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeProbationMDFDReject" +
            "s", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationMDFDRejects_Result> EmployeeProbationMDFDRejectsAsync(Mailer.EmployeeProbationMDFDRejects request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeProbationMDFDApprov" +
            "es", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationMDFDApproves_Result> EmployeeProbationMDFDApprovesAsync(Mailer.EmployeeProbationMDFDApproves request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeProbationHRApproves" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationHRApproves_Result> EmployeeProbationHRApprovesAsync(Mailer.EmployeeProbationHRApproves request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeEOCManagerToHR", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCManagerToHR_Result> EmployeeEOCManagerToHRAsync(Mailer.EmployeeEOCManagerToHR request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeEOCHRToMDFD", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCHRToMDFD_Result> EmployeeEOCHRToMDFDAsync(Mailer.EmployeeEOCHRToMDFD request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeEOCMDFDRejects", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCMDFDRejects_Result> EmployeeEOCMDFDRejectsAsync(Mailer.EmployeeEOCMDFDRejects request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeEOCMDFDApproves", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCMDFDApproves_Result> EmployeeEOCMDFDApprovesAsync(Mailer.EmployeeEOCMDFDApproves request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Notifications:EmployeeEOCHRApproves", ReplyAction="*")]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCHRApproves_Result> EmployeeEOCHRApprovesAsync(Mailer.EmployeeEOCHRApproves request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorMonth1", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorMonth1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public PerformanceMonitorMonth1()
        {
        }
        
        public PerformanceMonitorMonth1(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorMonth1_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorMonth1_Result
    {
        
        public PerformanceMonitorMonth1_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorMonth2", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorMonth2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public PerformanceMonitorMonth2()
        {
        }
        
        public PerformanceMonitorMonth2(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorMonth2_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorMonth2_Result
    {
        
        public PerformanceMonitorMonth2_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorMonth3", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorMonth3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public PerformanceMonitorMonth3()
        {
        }
        
        public PerformanceMonitorMonth3(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorMonth3_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorMonth3_Result
    {
        
        public PerformanceMonitorMonth3_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorApproval", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorApproval
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public PerformanceMonitorApproval()
        {
        }
        
        public PerformanceMonitorApproval(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorApproval_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorApproval_Result
    {
        
        public PerformanceMonitorApproval_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorRejection", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorRejection
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public PerformanceMonitorRejection()
        {
        }
        
        public PerformanceMonitorRejection(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitorRejection_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitorRejection_Result
    {
        
        public PerformanceMonitorRejection_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitortoHRfromHOD", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitortoHRfromHOD
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public PerformanceMonitortoHRfromHOD()
        {
        }
        
        public PerformanceMonitortoHRfromHOD(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PerformanceMonitortoHRfromHOD_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class PerformanceMonitortoHRfromHOD_Result
    {
        
        public PerformanceMonitortoHRfromHOD_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitiontoHRfromHOD", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitiontoHRfromHOD
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public StaffRequisitiontoHRfromHOD()
        {
        }
        
        public StaffRequisitiontoHRfromHOD(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitiontoHRfromHOD_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitiontoHRfromHOD_Result
    {
        
        public StaffRequisitiontoHRfromHOD_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitiontoMDfromHR", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitiontoMDfromHR
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public StaffRequisitiontoMDfromHR()
        {
        }
        
        public StaffRequisitiontoMDfromHR(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitiontoMDfromHR_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitiontoMDfromHR_Result
    {
        
        public StaffRequisitiontoMDfromHR_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitionHRApproval", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitionHRApproval
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public StaffRequisitionHRApproval()
        {
        }
        
        public StaffRequisitionHRApproval(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitionHRApproval_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitionHRApproval_Result
    {
        
        public StaffRequisitionHRApproval_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitionMDRejection", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitionMDRejection
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public StaffRequisitionMDRejection()
        {
        }
        
        public StaffRequisitionMDRejection(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitionMDRejection_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitionMDRejection_Result
    {
        
        public StaffRequisitionMDRejection_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitiontoHRfromMD", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitiontoHRfromMD
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public StaffRequisitiontoHRfromMD()
        {
        }
        
        public StaffRequisitiontoHRfromMD(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StaffRequisitiontoHRfromMD_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class StaffRequisitiontoHRfromMD_Result
    {
        
        public StaffRequisitiontoHRfromMD_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShortlistedInterviewNotice", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class ShortlistedInterviewNotice
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public ShortlistedInterviewNotice()
        {
        }
        
        public ShortlistedInterviewNotice(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShortlistedInterviewNotice_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class ShortlistedInterviewNotice_Result
    {
        
        public ShortlistedInterviewNotice_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationManagerToHR", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationManagerToHR
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeProbationManagerToHR()
        {
        }
        
        public EmployeeProbationManagerToHR(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationManagerToHR_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationManagerToHR_Result
    {
        
        public EmployeeProbationManagerToHR_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationHRToMDFD", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationHRToMDFD
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeProbationHRToMDFD()
        {
        }
        
        public EmployeeProbationHRToMDFD(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationHRToMDFD_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationHRToMDFD_Result
    {
        
        public EmployeeProbationHRToMDFD_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationMDFDRejects", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationMDFDRejects
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeProbationMDFDRejects()
        {
        }
        
        public EmployeeProbationMDFDRejects(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationMDFDRejects_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationMDFDRejects_Result
    {
        
        public EmployeeProbationMDFDRejects_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationMDFDApproves", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationMDFDApproves
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeProbationMDFDApproves()
        {
        }
        
        public EmployeeProbationMDFDApproves(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationMDFDApproves_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationMDFDApproves_Result
    {
        
        public EmployeeProbationMDFDApproves_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationHRApproves", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationHRApproves
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeProbationHRApproves()
        {
        }
        
        public EmployeeProbationHRApproves(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeProbationHRApproves_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeProbationHRApproves_Result
    {
        
        public EmployeeProbationHRApproves_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCManagerToHR", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCManagerToHR
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeEOCManagerToHR()
        {
        }
        
        public EmployeeEOCManagerToHR(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCManagerToHR_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCManagerToHR_Result
    {
        
        public EmployeeEOCManagerToHR_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCHRToMDFD", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCHRToMDFD
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeEOCHRToMDFD()
        {
        }
        
        public EmployeeEOCHRToMDFD(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCHRToMDFD_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCHRToMDFD_Result
    {
        
        public EmployeeEOCHRToMDFD_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCMDFDRejects", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCMDFDRejects
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeEOCMDFDRejects()
        {
        }
        
        public EmployeeEOCMDFDRejects(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCMDFDRejects_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCMDFDRejects_Result
    {
        
        public EmployeeEOCMDFDRejects_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCMDFDApproves", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCMDFDApproves
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeEOCMDFDApproves()
        {
        }
        
        public EmployeeEOCMDFDApproves(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCMDFDApproves_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCMDFDApproves_Result
    {
        
        public EmployeeEOCMDFDApproves_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCHRApproves", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCHRApproves
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", Order=0)]
        public string pKey;
        
        public EmployeeEOCHRApproves()
        {
        }
        
        public EmployeeEOCHRApproves(string pKey)
        {
            this.pKey = pKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeEOCHRApproves_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Notifications", IsWrapped=true)]
    public partial class EmployeeEOCHRApproves_Result
    {
        
        public EmployeeEOCHRApproves_Result()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface Notifications_PortChannel : Mailer.Notifications_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class Notifications_PortClient : System.ServiceModel.ClientBase<Mailer.Notifications_Port>, Mailer.Notifications_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Notifications_PortClient() : 
                base(Notifications_PortClient.GetDefaultBinding(), Notifications_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Notifications_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Notifications_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(Notifications_PortClient.GetBindingForEndpoint(endpointConfiguration), Notifications_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Notifications_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Notifications_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Notifications_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Notifications_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Notifications_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorMonth1_Result> Mailer.Notifications_Port.PerformanceMonitorMonth1Async(Mailer.PerformanceMonitorMonth1 request)
        {
            return base.Channel.PerformanceMonitorMonth1Async(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.PerformanceMonitorMonth1_Result> PerformanceMonitorMonth1Async(string pKey)
        {
            Mailer.PerformanceMonitorMonth1 inValue = new Mailer.PerformanceMonitorMonth1();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).PerformanceMonitorMonth1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorMonth2_Result> Mailer.Notifications_Port.PerformanceMonitorMonth2Async(Mailer.PerformanceMonitorMonth2 request)
        {
            return base.Channel.PerformanceMonitorMonth2Async(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.PerformanceMonitorMonth2_Result> PerformanceMonitorMonth2Async(string pKey)
        {
            Mailer.PerformanceMonitorMonth2 inValue = new Mailer.PerformanceMonitorMonth2();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).PerformanceMonitorMonth2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorMonth3_Result> Mailer.Notifications_Port.PerformanceMonitorMonth3Async(Mailer.PerformanceMonitorMonth3 request)
        {
            return base.Channel.PerformanceMonitorMonth3Async(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.PerformanceMonitorMonth3_Result> PerformanceMonitorMonth3Async(string pKey)
        {
            Mailer.PerformanceMonitorMonth3 inValue = new Mailer.PerformanceMonitorMonth3();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).PerformanceMonitorMonth3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorApproval_Result> Mailer.Notifications_Port.PerformanceMonitorApprovalAsync(Mailer.PerformanceMonitorApproval request)
        {
            return base.Channel.PerformanceMonitorApprovalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.PerformanceMonitorApproval_Result> PerformanceMonitorApprovalAsync(string pKey)
        {
            Mailer.PerformanceMonitorApproval inValue = new Mailer.PerformanceMonitorApproval();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).PerformanceMonitorApprovalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitorRejection_Result> Mailer.Notifications_Port.PerformanceMonitorRejectionAsync(Mailer.PerformanceMonitorRejection request)
        {
            return base.Channel.PerformanceMonitorRejectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.PerformanceMonitorRejection_Result> PerformanceMonitorRejectionAsync(string pKey)
        {
            Mailer.PerformanceMonitorRejection inValue = new Mailer.PerformanceMonitorRejection();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).PerformanceMonitorRejectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.PerformanceMonitortoHRfromHOD_Result> Mailer.Notifications_Port.PerformanceMonitortoHRfromHODAsync(Mailer.PerformanceMonitortoHRfromHOD request)
        {
            return base.Channel.PerformanceMonitortoHRfromHODAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.PerformanceMonitortoHRfromHOD_Result> PerformanceMonitortoHRfromHODAsync(string pKey)
        {
            Mailer.PerformanceMonitortoHRfromHOD inValue = new Mailer.PerformanceMonitortoHRfromHOD();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).PerformanceMonitortoHRfromHODAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.StaffRequisitiontoHRfromHOD_Result> Mailer.Notifications_Port.StaffRequisitiontoHRfromHODAsync(Mailer.StaffRequisitiontoHRfromHOD request)
        {
            return base.Channel.StaffRequisitiontoHRfromHODAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.StaffRequisitiontoHRfromHOD_Result> StaffRequisitiontoHRfromHODAsync(string pKey)
        {
            Mailer.StaffRequisitiontoHRfromHOD inValue = new Mailer.StaffRequisitiontoHRfromHOD();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).StaffRequisitiontoHRfromHODAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.StaffRequisitiontoMDfromHR_Result> Mailer.Notifications_Port.StaffRequisitiontoMDfromHRAsync(Mailer.StaffRequisitiontoMDfromHR request)
        {
            return base.Channel.StaffRequisitiontoMDfromHRAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.StaffRequisitiontoMDfromHR_Result> StaffRequisitiontoMDfromHRAsync(string pKey)
        {
            Mailer.StaffRequisitiontoMDfromHR inValue = new Mailer.StaffRequisitiontoMDfromHR();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).StaffRequisitiontoMDfromHRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.StaffRequisitionHRApproval_Result> Mailer.Notifications_Port.StaffRequisitionHRApprovalAsync(Mailer.StaffRequisitionHRApproval request)
        {
            return base.Channel.StaffRequisitionHRApprovalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.StaffRequisitionHRApproval_Result> StaffRequisitionHRApprovalAsync(string pKey)
        {
            Mailer.StaffRequisitionHRApproval inValue = new Mailer.StaffRequisitionHRApproval();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).StaffRequisitionHRApprovalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.StaffRequisitionMDRejection_Result> Mailer.Notifications_Port.StaffRequisitionMDRejectionAsync(Mailer.StaffRequisitionMDRejection request)
        {
            return base.Channel.StaffRequisitionMDRejectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.StaffRequisitionMDRejection_Result> StaffRequisitionMDRejectionAsync(string pKey)
        {
            Mailer.StaffRequisitionMDRejection inValue = new Mailer.StaffRequisitionMDRejection();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).StaffRequisitionMDRejectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.StaffRequisitiontoHRfromMD_Result> Mailer.Notifications_Port.StaffRequisitiontoHRfromMDAsync(Mailer.StaffRequisitiontoHRfromMD request)
        {
            return base.Channel.StaffRequisitiontoHRfromMDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.StaffRequisitiontoHRfromMD_Result> StaffRequisitiontoHRfromMDAsync(string pKey)
        {
            Mailer.StaffRequisitiontoHRfromMD inValue = new Mailer.StaffRequisitiontoHRfromMD();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).StaffRequisitiontoHRfromMDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.ShortlistedInterviewNotice_Result> Mailer.Notifications_Port.ShortlistedInterviewNoticeAsync(Mailer.ShortlistedInterviewNotice request)
        {
            return base.Channel.ShortlistedInterviewNoticeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.ShortlistedInterviewNotice_Result> ShortlistedInterviewNoticeAsync(string pKey)
        {
            Mailer.ShortlistedInterviewNotice inValue = new Mailer.ShortlistedInterviewNotice();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).ShortlistedInterviewNoticeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationManagerToHR_Result> Mailer.Notifications_Port.EmployeeProbationManagerToHRAsync(Mailer.EmployeeProbationManagerToHR request)
        {
            return base.Channel.EmployeeProbationManagerToHRAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeProbationManagerToHR_Result> EmployeeProbationManagerToHRAsync(string pKey)
        {
            Mailer.EmployeeProbationManagerToHR inValue = new Mailer.EmployeeProbationManagerToHR();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeProbationManagerToHRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationHRToMDFD_Result> Mailer.Notifications_Port.EmployeeProbationHRToMDFDAsync(Mailer.EmployeeProbationHRToMDFD request)
        {
            return base.Channel.EmployeeProbationHRToMDFDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeProbationHRToMDFD_Result> EmployeeProbationHRToMDFDAsync(string pKey)
        {
            Mailer.EmployeeProbationHRToMDFD inValue = new Mailer.EmployeeProbationHRToMDFD();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeProbationHRToMDFDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationMDFDRejects_Result> Mailer.Notifications_Port.EmployeeProbationMDFDRejectsAsync(Mailer.EmployeeProbationMDFDRejects request)
        {
            return base.Channel.EmployeeProbationMDFDRejectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeProbationMDFDRejects_Result> EmployeeProbationMDFDRejectsAsync(string pKey)
        {
            Mailer.EmployeeProbationMDFDRejects inValue = new Mailer.EmployeeProbationMDFDRejects();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeProbationMDFDRejectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationMDFDApproves_Result> Mailer.Notifications_Port.EmployeeProbationMDFDApprovesAsync(Mailer.EmployeeProbationMDFDApproves request)
        {
            return base.Channel.EmployeeProbationMDFDApprovesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeProbationMDFDApproves_Result> EmployeeProbationMDFDApprovesAsync(string pKey)
        {
            Mailer.EmployeeProbationMDFDApproves inValue = new Mailer.EmployeeProbationMDFDApproves();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeProbationMDFDApprovesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeProbationHRApproves_Result> Mailer.Notifications_Port.EmployeeProbationHRApprovesAsync(Mailer.EmployeeProbationHRApproves request)
        {
            return base.Channel.EmployeeProbationHRApprovesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeProbationHRApproves_Result> EmployeeProbationHRApprovesAsync(string pKey)
        {
            Mailer.EmployeeProbationHRApproves inValue = new Mailer.EmployeeProbationHRApproves();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeProbationHRApprovesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCManagerToHR_Result> Mailer.Notifications_Port.EmployeeEOCManagerToHRAsync(Mailer.EmployeeEOCManagerToHR request)
        {
            return base.Channel.EmployeeEOCManagerToHRAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeEOCManagerToHR_Result> EmployeeEOCManagerToHRAsync(string pKey)
        {
            Mailer.EmployeeEOCManagerToHR inValue = new Mailer.EmployeeEOCManagerToHR();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeEOCManagerToHRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCHRToMDFD_Result> Mailer.Notifications_Port.EmployeeEOCHRToMDFDAsync(Mailer.EmployeeEOCHRToMDFD request)
        {
            return base.Channel.EmployeeEOCHRToMDFDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeEOCHRToMDFD_Result> EmployeeEOCHRToMDFDAsync(string pKey)
        {
            Mailer.EmployeeEOCHRToMDFD inValue = new Mailer.EmployeeEOCHRToMDFD();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeEOCHRToMDFDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCMDFDRejects_Result> Mailer.Notifications_Port.EmployeeEOCMDFDRejectsAsync(Mailer.EmployeeEOCMDFDRejects request)
        {
            return base.Channel.EmployeeEOCMDFDRejectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeEOCMDFDRejects_Result> EmployeeEOCMDFDRejectsAsync(string pKey)
        {
            Mailer.EmployeeEOCMDFDRejects inValue = new Mailer.EmployeeEOCMDFDRejects();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeEOCMDFDRejectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCMDFDApproves_Result> Mailer.Notifications_Port.EmployeeEOCMDFDApprovesAsync(Mailer.EmployeeEOCMDFDApproves request)
        {
            return base.Channel.EmployeeEOCMDFDApprovesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeEOCMDFDApproves_Result> EmployeeEOCMDFDApprovesAsync(string pKey)
        {
            Mailer.EmployeeEOCMDFDApproves inValue = new Mailer.EmployeeEOCMDFDApproves();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeEOCMDFDApprovesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mailer.EmployeeEOCHRApproves_Result> Mailer.Notifications_Port.EmployeeEOCHRApprovesAsync(Mailer.EmployeeEOCHRApproves request)
        {
            return base.Channel.EmployeeEOCHRApprovesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mailer.EmployeeEOCHRApproves_Result> EmployeeEOCHRApprovesAsync(string pKey)
        {
            Mailer.EmployeeEOCHRApproves inValue = new Mailer.EmployeeEOCHRApproves();
            inValue.pKey = pKey;
            return ((Mailer.Notifications_Port)(this)).EmployeeEOCHRApprovesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Notifications_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Notifications_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://desktop-csglh1r:7347/PLATCORP/WS/Platcorp Training/Codeunit/Notifications");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Notifications_PortClient.GetBindingForEndpoint(EndpointConfiguration.Notifications_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Notifications_PortClient.GetEndpointAddress(EndpointConfiguration.Notifications_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            Notifications_Port,
        }
    }
}
